# Generated by Django 5.1.7 on 2025-03-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollnumber',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
